import React, { Component, useState, useEffect} from 'react';
import './App.css';
import axios from 'axios'
import { MathComponent } from "mathjax-react";
//import Plot from 'react-plotly.js';
import {Mafs, Coordinates, Plot, Theme, useMovablePoint, MovablePoint, vec, Text} from "mafs"
import 'mafs/core.css'
import {
  atan2, chain, derivative, e, evaluate, expression, log, pi, pow, round, sqrt
} from 'mathjs'
//import {Mafs, Coordinates, Plot, Theme, useMovablePoint, MovablePoint, vec, Text} from "mafs"


function MVTDesc(){
  return(
    <div>
    <h3>The Fixed Point Iteration</h3>
    <br></br>
    <p>
      The fixed point method is an iterative method that seeks to find a point <i>p</i> in a domain <i>[a,b]</i> where <i>f(p) = p</i>. 
      This information can be used to find a zero of a non-linear function. The points generated by each iteration are formed by plugging in 
      the previous iterantion into a given function g(x). Hence, for the fixed-point family of numerical methods the following is a commonality
       <MathComponent tex={String.raw`p_{n+1} = g(p_n)`}/>
    </p>

    <p>The function used for the fixed point iterations must be main an interval in its domain <i>[a,b]</i> to itself 
    in order to be eligible to converge in the fixed point. If this mapping is true, then there must be a point 
    <i>p</i> in <i>[a,b]</i> such that <i>f(p) = p</i>.</p>
    <br></br>
    <p>Suppose that <i>f</i> is differentiable over the interval and and there exists a <i> 0 &lt; k &lt; 1</i> such 
    that for all <i>x</i> in the interval <i>[a,b]</i>, <i>f'(x) &le; k.</i> </p>
    <p>
      Recall that the mean value theorem states for 
    </p>

    </div> 




  )




}

class MainForm extends Component{
  constructor(props){
    super(props); 
  }

  render(){
    return(
    <div>
      <MVTDesc/>
    </div>
    )
  }

}





class App extends Component {
  render() {
    return (
      <div> 
      <h1 id = "title">Global Interpolation</h1>  
      <MainForm />
      </div>
      
    );
  }
}
export default App;